Link example headers to corresponding files/links
lob/lob-ruby pull request #184
Opened 2020-08-24 16:15 UTC by mtvillwock

Allow users to click through to the referenced file instead of having to scroll up to the page.

2021-02-17 02:33 UTC, ajorczak-lob commented on examples/README.md
> +## [/checks.rb](./letters.rb)
Reference should be `./checks.rb`here

2021-02-17 02:35 UTC, ajorczak-lob requested changes
Thanks for providing an easy way for our users to navigate! Had one quick comment below before we merge in!

2021-12-17 19:03 UTC, SidneyAllen approved these changes

2021-12-17 19:16 UTC, ShariqT commented
Resolved in https://github.com/lob/lob-ruby/pull/195

2021-12-17 19:16 UTC, closed without merging