Refactor ResourceBase to make the options sent to rest-client more configurable
lob/lob-ruby pull request #199
Opened 2021-12-08 22:21 UTC by drcapulet

I need to be able to configure a proxy for rest-client on a per-client basis so I refactored this first to normalize between different request methods.

2021-12-08 23:09 UTC, colin-garcia approved these changes

2021-12-11 00:17 UTC, ShariqT commented
Thanks for the interest in Lob. So, we are looking at the PR and it looks like this will add `body` content to the GET and DELETE methods. That's something that we are not really prepared to do at the moment. Can you explain what you want to be able to do a little bit more and how the `body` content will allow this?

2021-12-11 00:24 UTC, mwj8410 requested changes

2021-12-11 00:24 UTC, mwj8410 commented on lib/lob/resources/resource_base.rb
> -          if method == :get || method == :delete
Can we wrap the assignment to `client_params[:body]` with these 2 cases please?

GET and DELETE operations are intended by specification to only leverage the URI. Removing this case enables passing a body in these requests. Although it isn't specifically prohibited it the spec, it is intended to be functionally irrelevant.

Ref: [https://www.rfc-editor.org/rfc/rfc2616#section-9.3](https://www.rfc-editor.org/rfc/rfc2616#section-9.3)

2021-12-11 03:50 UTC, drcapulet commented
Ah to clarify - the change isn't intending to set body for `GET` or `DELETE` and I can certainly add back that guard (though practically it'd be an issue with the caller anyways). As I noted in the PR description, I need to be able to pass rest-client a [proxy](https://github.com/rest-client/rest-client#proxy) and the `RestClient.get` variety methods don't support that so I decided to normalize things for the `RestClient::Request.execute` call.

2021-12-14 22:55 UTC, mwj8410 approved these changes
Perfect. Thank very much

2021-12-15 16:00 UTC, merged

2021-12-16 23:16 UTC, ShariqT commented
Thanks for the contribution! We have merged this piece of code and are looking over the other PR you submitted as well.